-- =============================================================================
--  F-122 (R-24 / R-25 / R-26 - DT-04 opcion b) -- CARGA DE `locations_reference`
-- =============================================================================
--
--  PROCEDENCIA DE LA LISTA  (declarada aca porque la carga tiene que ser REVISABLE,
--  re-ejecutable y auditable -- no un pegado a la consola).
--
--    - Fuente ...... enumeracion por condado compilada por el implementer de F-122.
--                    /!\ NO se descargo ni se verifico contra un padron oficial
--                    (California Secretary of State / CSAC). El operador DEBE
--                    revisarla antes de ejecutarla (T-18, tramo LIVE gateado).
--    - Fecha ....... 2026-07-28
--    - Criterio de inclusion ... municipios INCORPORADOS de California (cities y
--                    towns). NO incluye census-designated places, comunidades no
--                    incorporadas ni barrios.
--    - Alcance ..... 482 ciudades en 55 condados. El total coincide con el numero
--                    de municipios incorporados de California habitualmente citado
--                    (482): es una senal de consistencia, NO una prueba de completitud.
--
--  LO QUE ESTE ARCHIVO **NO** PROMETE  (R-27, y la regla de no prometer falsa nitidez)
--    La completitud de un padron externo no es auditable desde este repo. El criterio
--    de aceptacion es VERIFICABLE, no aspiracional:
--      (i)   cero duplicados por `(city, state)`;
--      (ii)  el conteo crece respecto de las 57 filas actuales;
--      (iii) toda `clients.city` no-marcador existe en el catalogo
--            (hoy: `Buellton` y `Santa Maria`, ambas YA presentes => no se re-insertan).
--
--  IDEMPOTENCIA -- POR QUE **NO** HAY `ON CONFLICT`  (E-4 / H-1 / R-25)
--    `locations_reference` **no tiene unique constraint** sobre `(city, state)`:
--    `pg_constraint` devuelve exactamente una fila, `locations_reference_pkey (id)`.
--    `ON CONFLICT` NO es aplicable, y **crear la constraint seria DDL** (R-05, prohibido).
--    La guarda es `WHERE NOT EXISTS`. Sin ella, una segunda corrida duplicaria filas --
--    y un duplicado ademas rompe `key=loc.city` en el `<select>` del Brief (H-2).
--
--  LO QUE ESTE ARCHIVO NO HACE  (R-26)
--    Ni un UPDATE, ni un DELETE, ni DDL. **Solo INSERT.** Las 57 filas actuales quedan
--    intactas, incluidas `Buellton` y `Santa Maria`, que son las ciudades reales de dos
--    clientes. `zip_codes` queda en su default, `state` en 'CA', `active` en true.
--
--  EJECUCION -- accion de FRONTERA, gateada (F-074): tarea T-18 del tramo LIVE.
--    Se corre DOS VECES: la segunda no debe insertar nada. Esa es la prueba real de la
--    idempotencia sin unique constraint.
-- =============================================================================

INSERT INTO locations_reference (city, county, state)
SELECT c.city, c.county, 'CA'
FROM (VALUES
  ('Alameda', 'Alameda'),
  ('Albany', 'Alameda'),
  ('Berkeley', 'Alameda'),
  ('Dublin', 'Alameda'),
  ('Emeryville', 'Alameda'),
  ('Fremont', 'Alameda'),
  ('Hayward', 'Alameda'),
  ('Livermore', 'Alameda'),
  ('Newark', 'Alameda'),
  ('Oakland', 'Alameda'),
  ('Piedmont', 'Alameda'),
  ('Pleasanton', 'Alameda'),
  ('San Leandro', 'Alameda'),
  ('Union City', 'Alameda'),
  ('Amador City', 'Amador'),
  ('Ione', 'Amador'),
  ('Jackson', 'Amador'),
  ('Plymouth', 'Amador'),
  ('Sutter Creek', 'Amador'),
  ('Biggs', 'Butte'),
  ('Chico', 'Butte'),
  ('Gridley', 'Butte'),
  ('Oroville', 'Butte'),
  ('Paradise', 'Butte'),
  ('Angels Camp', 'Calaveras'),
  ('Colusa', 'Colusa'),
  ('Williams', 'Colusa'),
  ('Antioch', 'Contra Costa'),
  ('Brentwood', 'Contra Costa'),
  ('Clayton', 'Contra Costa'),
  ('Concord', 'Contra Costa'),
  ('Danville', 'Contra Costa'),
  ('El Cerrito', 'Contra Costa'),
  ('Hercules', 'Contra Costa'),
  ('Lafayette', 'Contra Costa'),
  ('Martinez', 'Contra Costa'),
  ('Moraga', 'Contra Costa'),
  ('Oakley', 'Contra Costa'),
  ('Orinda', 'Contra Costa'),
  ('Pinole', 'Contra Costa'),
  ('Pittsburg', 'Contra Costa'),
  ('Pleasant Hill', 'Contra Costa'),
  ('Richmond', 'Contra Costa'),
  ('San Pablo', 'Contra Costa'),
  ('San Ramon', 'Contra Costa'),
  ('Walnut Creek', 'Contra Costa'),
  ('Crescent City', 'Del Norte'),
  ('Placerville', 'El Dorado'),
  ('South Lake Tahoe', 'El Dorado'),
  ('Clovis', 'Fresno'),
  ('Coalinga', 'Fresno'),
  ('Firebaugh', 'Fresno'),
  ('Fowler', 'Fresno'),
  ('Fresno', 'Fresno'),
  ('Huron', 'Fresno'),
  ('Kerman', 'Fresno'),
  ('Kingsburg', 'Fresno'),
  ('Mendota', 'Fresno'),
  ('Orange Cove', 'Fresno'),
  ('Parlier', 'Fresno'),
  ('Reedley', 'Fresno'),
  ('San Joaquin', 'Fresno'),
  ('Sanger', 'Fresno'),
  ('Selma', 'Fresno'),
  ('Orland', 'Glenn'),
  ('Willows', 'Glenn'),
  ('Arcata', 'Humboldt'),
  ('Blue Lake', 'Humboldt'),
  ('Eureka', 'Humboldt'),
  ('Ferndale', 'Humboldt'),
  ('Fortuna', 'Humboldt'),
  ('Rio Dell', 'Humboldt'),
  ('Trinidad', 'Humboldt'),
  ('Brawley', 'Imperial'),
  ('Calexico', 'Imperial'),
  ('Calipatria', 'Imperial'),
  ('El Centro', 'Imperial'),
  ('Holtville', 'Imperial'),
  ('Imperial', 'Imperial'),
  ('Westmorland', 'Imperial'),
  ('Bishop', 'Inyo'),
  ('Arvin', 'Kern'),
  ('Bakersfield', 'Kern'),
  ('California City', 'Kern'),
  ('Delano', 'Kern'),
  ('Maricopa', 'Kern'),
  ('McFarland', 'Kern'),
  ('Ridgecrest', 'Kern'),
  ('Shafter', 'Kern'),
  ('Taft', 'Kern'),
  ('Tehachapi', 'Kern'),
  ('Wasco', 'Kern'),
  ('Avenal', 'Kings'),
  ('Corcoran', 'Kings'),
  ('Hanford', 'Kings'),
  ('Lemoore', 'Kings'),
  ('Clearlake', 'Lake'),
  ('Lakeport', 'Lake'),
  ('Susanville', 'Lassen'),
  ('Agoura Hills', 'Los Angeles'),
  ('Alhambra', 'Los Angeles'),
  ('Arcadia', 'Los Angeles'),
  ('Artesia', 'Los Angeles'),
  ('Avalon', 'Los Angeles'),
  ('Azusa', 'Los Angeles'),
  ('Baldwin Park', 'Los Angeles'),
  ('Bell', 'Los Angeles'),
  ('Bell Gardens', 'Los Angeles'),
  ('Bellflower', 'Los Angeles'),
  ('Beverly Hills', 'Los Angeles'),
  ('Bradbury', 'Los Angeles'),
  ('Burbank', 'Los Angeles'),
  ('Calabasas', 'Los Angeles'),
  ('Carson', 'Los Angeles'),
  ('Cerritos', 'Los Angeles'),
  ('Claremont', 'Los Angeles'),
  ('Commerce', 'Los Angeles'),
  ('Compton', 'Los Angeles'),
  ('Covina', 'Los Angeles'),
  ('Cudahy', 'Los Angeles'),
  ('Culver City', 'Los Angeles'),
  ('Diamond Bar', 'Los Angeles'),
  ('Downey', 'Los Angeles'),
  ('Duarte', 'Los Angeles'),
  ('El Monte', 'Los Angeles'),
  ('El Segundo', 'Los Angeles'),
  ('Gardena', 'Los Angeles'),
  ('Glendale', 'Los Angeles'),
  ('Glendora', 'Los Angeles'),
  ('Hawaiian Gardens', 'Los Angeles'),
  ('Hawthorne', 'Los Angeles'),
  ('Hermosa Beach', 'Los Angeles'),
  ('Hidden Hills', 'Los Angeles'),
  ('Huntington Park', 'Los Angeles'),
  ('Industry', 'Los Angeles'),
  ('Inglewood', 'Los Angeles'),
  ('Irwindale', 'Los Angeles'),
  ('La Cañada Flintridge', 'Los Angeles'),
  ('La Habra Heights', 'Los Angeles'),
  ('La Mirada', 'Los Angeles'),
  ('La Puente', 'Los Angeles'),
  ('La Verne', 'Los Angeles'),
  ('Lakewood', 'Los Angeles'),
  ('Lancaster', 'Los Angeles'),
  ('Lawndale', 'Los Angeles'),
  ('Lomita', 'Los Angeles'),
  ('Long Beach', 'Los Angeles'),
  ('Los Angeles', 'Los Angeles'),
  ('Lynwood', 'Los Angeles'),
  ('Malibu', 'Los Angeles'),
  ('Manhattan Beach', 'Los Angeles'),
  ('Maywood', 'Los Angeles'),
  ('Monrovia', 'Los Angeles'),
  ('Montebello', 'Los Angeles'),
  ('Monterey Park', 'Los Angeles'),
  ('Norwalk', 'Los Angeles'),
  ('Palmdale', 'Los Angeles'),
  ('Palos Verdes Estates', 'Los Angeles'),
  ('Paramount', 'Los Angeles'),
  ('Pasadena', 'Los Angeles'),
  ('Pico Rivera', 'Los Angeles'),
  ('Pomona', 'Los Angeles'),
  ('Rancho Palos Verdes', 'Los Angeles'),
  ('Redondo Beach', 'Los Angeles'),
  ('Rolling Hills', 'Los Angeles'),
  ('Rolling Hills Estates', 'Los Angeles'),
  ('Rosemead', 'Los Angeles'),
  ('San Dimas', 'Los Angeles'),
  ('San Fernando', 'Los Angeles'),
  ('San Gabriel', 'Los Angeles'),
  ('San Marino', 'Los Angeles'),
  ('Santa Clarita', 'Los Angeles'),
  ('Santa Fe Springs', 'Los Angeles'),
  ('Santa Monica', 'Los Angeles'),
  ('Sierra Madre', 'Los Angeles'),
  ('Signal Hill', 'Los Angeles'),
  ('South El Monte', 'Los Angeles'),
  ('South Gate', 'Los Angeles'),
  ('South Pasadena', 'Los Angeles'),
  ('Temple City', 'Los Angeles'),
  ('Torrance', 'Los Angeles'),
  ('Vernon', 'Los Angeles'),
  ('Walnut', 'Los Angeles'),
  ('West Covina', 'Los Angeles'),
  ('West Hollywood', 'Los Angeles'),
  ('Westlake Village', 'Los Angeles'),
  ('Whittier', 'Los Angeles'),
  ('Chowchilla', 'Madera'),
  ('Madera', 'Madera'),
  ('Belvedere', 'Marin'),
  ('Corte Madera', 'Marin'),
  ('Fairfax', 'Marin'),
  ('Larkspur', 'Marin'),
  ('Mill Valley', 'Marin'),
  ('Novato', 'Marin'),
  ('Ross', 'Marin'),
  ('San Anselmo', 'Marin'),
  ('San Rafael', 'Marin'),
  ('Sausalito', 'Marin'),
  ('Tiburon', 'Marin'),
  ('Fort Bragg', 'Mendocino'),
  ('Point Arena', 'Mendocino'),
  ('Ukiah', 'Mendocino'),
  ('Willits', 'Mendocino'),
  ('Atwater', 'Merced'),
  ('Dos Palos', 'Merced'),
  ('Gustine', 'Merced'),
  ('Livingston', 'Merced'),
  ('Los Banos', 'Merced'),
  ('Merced', 'Merced'),
  ('Alturas', 'Modoc'),
  ('Mammoth Lakes', 'Mono'),
  ('Carmel-by-the-Sea', 'Monterey'),
  ('Del Rey Oaks', 'Monterey'),
  ('Gonzales', 'Monterey'),
  ('Greenfield', 'Monterey'),
  ('King City', 'Monterey'),
  ('Marina', 'Monterey'),
  ('Monterey', 'Monterey'),
  ('Pacific Grove', 'Monterey'),
  ('Salinas', 'Monterey'),
  ('Sand City', 'Monterey'),
  ('Seaside', 'Monterey'),
  ('Soledad', 'Monterey'),
  ('American Canyon', 'Napa'),
  ('Calistoga', 'Napa'),
  ('Napa', 'Napa'),
  ('St. Helena', 'Napa'),
  ('Yountville', 'Napa'),
  ('Grass Valley', 'Nevada'),
  ('Nevada City', 'Nevada'),
  ('Truckee', 'Nevada'),
  ('Aliso Viejo', 'Orange'),
  ('Anaheim', 'Orange'),
  ('Brea', 'Orange'),
  ('Buena Park', 'Orange'),
  ('Costa Mesa', 'Orange'),
  ('Cypress', 'Orange'),
  ('Dana Point', 'Orange'),
  ('Fountain Valley', 'Orange'),
  ('Fullerton', 'Orange'),
  ('Garden Grove', 'Orange'),
  ('Huntington Beach', 'Orange'),
  ('Irvine', 'Orange'),
  ('La Habra', 'Orange'),
  ('La Palma', 'Orange'),
  ('Laguna Beach', 'Orange'),
  ('Laguna Hills', 'Orange'),
  ('Laguna Niguel', 'Orange'),
  ('Laguna Woods', 'Orange'),
  ('Lake Forest', 'Orange'),
  ('Los Alamitos', 'Orange'),
  ('Mission Viejo', 'Orange'),
  ('Newport Beach', 'Orange'),
  ('Orange', 'Orange'),
  ('Placentia', 'Orange'),
  ('Rancho Santa Margarita', 'Orange'),
  ('San Clemente', 'Orange'),
  ('San Juan Capistrano', 'Orange'),
  ('Santa Ana', 'Orange'),
  ('Seal Beach', 'Orange'),
  ('Stanton', 'Orange'),
  ('Tustin', 'Orange'),
  ('Villa Park', 'Orange'),
  ('Westminster', 'Orange'),
  ('Yorba Linda', 'Orange'),
  ('Auburn', 'Placer'),
  ('Colfax', 'Placer'),
  ('Lincoln', 'Placer'),
  ('Loomis', 'Placer'),
  ('Rocklin', 'Placer'),
  ('Roseville', 'Placer'),
  ('Portola', 'Plumas'),
  ('Banning', 'Riverside'),
  ('Beaumont', 'Riverside'),
  ('Blythe', 'Riverside'),
  ('Calimesa', 'Riverside'),
  ('Canyon Lake', 'Riverside'),
  ('Cathedral City', 'Riverside'),
  ('Coachella', 'Riverside'),
  ('Corona', 'Riverside'),
  ('Desert Hot Springs', 'Riverside'),
  ('Eastvale', 'Riverside'),
  ('Hemet', 'Riverside'),
  ('Indian Wells', 'Riverside'),
  ('Indio', 'Riverside'),
  ('Jurupa Valley', 'Riverside'),
  ('La Quinta', 'Riverside'),
  ('Lake Elsinore', 'Riverside'),
  ('Menifee', 'Riverside'),
  ('Moreno Valley', 'Riverside'),
  ('Murrieta', 'Riverside'),
  ('Norco', 'Riverside'),
  ('Palm Desert', 'Riverside'),
  ('Palm Springs', 'Riverside'),
  ('Perris', 'Riverside'),
  ('Rancho Mirage', 'Riverside'),
  ('Riverside', 'Riverside'),
  ('San Jacinto', 'Riverside'),
  ('Temecula', 'Riverside'),
  ('Wildomar', 'Riverside'),
  ('Citrus Heights', 'Sacramento'),
  ('Elk Grove', 'Sacramento'),
  ('Folsom', 'Sacramento'),
  ('Galt', 'Sacramento'),
  ('Isleton', 'Sacramento'),
  ('Rancho Cordova', 'Sacramento'),
  ('Sacramento', 'Sacramento'),
  ('Hollister', 'San Benito'),
  ('San Juan Bautista', 'San Benito'),
  ('Adelanto', 'San Bernardino'),
  ('Apple Valley', 'San Bernardino'),
  ('Barstow', 'San Bernardino'),
  ('Big Bear Lake', 'San Bernardino'),
  ('Chino', 'San Bernardino'),
  ('Chino Hills', 'San Bernardino'),
  ('Colton', 'San Bernardino'),
  ('Fontana', 'San Bernardino'),
  ('Grand Terrace', 'San Bernardino'),
  ('Hesperia', 'San Bernardino'),
  ('Highland', 'San Bernardino'),
  ('Loma Linda', 'San Bernardino'),
  ('Montclair', 'San Bernardino'),
  ('Needles', 'San Bernardino'),
  ('Ontario', 'San Bernardino'),
  ('Rancho Cucamonga', 'San Bernardino'),
  ('Redlands', 'San Bernardino'),
  ('Rialto', 'San Bernardino'),
  ('San Bernardino', 'San Bernardino'),
  ('Twentynine Palms', 'San Bernardino'),
  ('Upland', 'San Bernardino'),
  ('Victorville', 'San Bernardino'),
  ('Yucaipa', 'San Bernardino'),
  ('Yucca Valley', 'San Bernardino'),
  ('Carlsbad', 'San Diego'),
  ('Chula Vista', 'San Diego'),
  ('Coronado', 'San Diego'),
  ('Del Mar', 'San Diego'),
  ('El Cajon', 'San Diego'),
  ('Encinitas', 'San Diego'),
  ('Escondido', 'San Diego'),
  ('Imperial Beach', 'San Diego'),
  ('La Mesa', 'San Diego'),
  ('Lemon Grove', 'San Diego'),
  ('National City', 'San Diego'),
  ('Oceanside', 'San Diego'),
  ('Poway', 'San Diego'),
  ('San Diego', 'San Diego'),
  ('San Marcos', 'San Diego'),
  ('Santee', 'San Diego'),
  ('Solana Beach', 'San Diego'),
  ('Vista', 'San Diego'),
  ('San Francisco', 'San Francisco'),
  ('Escalon', 'San Joaquin'),
  ('Lathrop', 'San Joaquin'),
  ('Lodi', 'San Joaquin'),
  ('Manteca', 'San Joaquin'),
  ('Ripon', 'San Joaquin'),
  ('Stockton', 'San Joaquin'),
  ('Tracy', 'San Joaquin'),
  ('Arroyo Grande', 'San Luis Obispo'),
  ('Atascadero', 'San Luis Obispo'),
  ('Grover Beach', 'San Luis Obispo'),
  ('Morro Bay', 'San Luis Obispo'),
  ('Paso Robles', 'San Luis Obispo'),
  ('Pismo Beach', 'San Luis Obispo'),
  ('San Luis Obispo', 'San Luis Obispo'),
  ('Atherton', 'San Mateo'),
  ('Belmont', 'San Mateo'),
  ('Brisbane', 'San Mateo'),
  ('Burlingame', 'San Mateo'),
  ('Colma', 'San Mateo'),
  ('Daly City', 'San Mateo'),
  ('East Palo Alto', 'San Mateo'),
  ('Foster City', 'San Mateo'),
  ('Half Moon Bay', 'San Mateo'),
  ('Hillsborough', 'San Mateo'),
  ('Menlo Park', 'San Mateo'),
  ('Millbrae', 'San Mateo'),
  ('Pacifica', 'San Mateo'),
  ('Portola Valley', 'San Mateo'),
  ('Redwood City', 'San Mateo'),
  ('San Bruno', 'San Mateo'),
  ('San Carlos', 'San Mateo'),
  ('San Mateo', 'San Mateo'),
  ('South San Francisco', 'San Mateo'),
  ('Woodside', 'San Mateo'),
  ('Buellton', 'Santa Barbara'),
  ('Carpinteria', 'Santa Barbara'),
  ('Goleta', 'Santa Barbara'),
  ('Guadalupe', 'Santa Barbara'),
  ('Lompoc', 'Santa Barbara'),
  ('Santa Barbara', 'Santa Barbara'),
  ('Santa Maria', 'Santa Barbara'),
  ('Solvang', 'Santa Barbara'),
  ('Campbell', 'Santa Clara'),
  ('Cupertino', 'Santa Clara'),
  ('Gilroy', 'Santa Clara'),
  ('Los Altos', 'Santa Clara'),
  ('Los Altos Hills', 'Santa Clara'),
  ('Los Gatos', 'Santa Clara'),
  ('Milpitas', 'Santa Clara'),
  ('Monte Sereno', 'Santa Clara'),
  ('Morgan Hill', 'Santa Clara'),
  ('Mountain View', 'Santa Clara'),
  ('Palo Alto', 'Santa Clara'),
  ('San Jose', 'Santa Clara'),
  ('Santa Clara', 'Santa Clara'),
  ('Saratoga', 'Santa Clara'),
  ('Sunnyvale', 'Santa Clara'),
  ('Capitola', 'Santa Cruz'),
  ('Santa Cruz', 'Santa Cruz'),
  ('Scotts Valley', 'Santa Cruz'),
  ('Watsonville', 'Santa Cruz'),
  ('Anderson', 'Shasta'),
  ('Redding', 'Shasta'),
  ('Shasta Lake', 'Shasta'),
  ('Loyalton', 'Sierra'),
  ('Dorris', 'Siskiyou'),
  ('Dunsmuir', 'Siskiyou'),
  ('Etna', 'Siskiyou'),
  ('Fort Jones', 'Siskiyou'),
  ('Montague', 'Siskiyou'),
  ('Mount Shasta', 'Siskiyou'),
  ('Tulelake', 'Siskiyou'),
  ('Weed', 'Siskiyou'),
  ('Yreka', 'Siskiyou'),
  ('Benicia', 'Solano'),
  ('Dixon', 'Solano'),
  ('Fairfield', 'Solano'),
  ('Rio Vista', 'Solano'),
  ('Suisun City', 'Solano'),
  ('Vacaville', 'Solano'),
  ('Vallejo', 'Solano'),
  ('Cloverdale', 'Sonoma'),
  ('Cotati', 'Sonoma'),
  ('Healdsburg', 'Sonoma'),
  ('Petaluma', 'Sonoma'),
  ('Rohnert Park', 'Sonoma'),
  ('Santa Rosa', 'Sonoma'),
  ('Sebastopol', 'Sonoma'),
  ('Sonoma', 'Sonoma'),
  ('Windsor', 'Sonoma'),
  ('Ceres', 'Stanislaus'),
  ('Hughson', 'Stanislaus'),
  ('Modesto', 'Stanislaus'),
  ('Newman', 'Stanislaus'),
  ('Oakdale', 'Stanislaus'),
  ('Patterson', 'Stanislaus'),
  ('Riverbank', 'Stanislaus'),
  ('Turlock', 'Stanislaus'),
  ('Waterford', 'Stanislaus'),
  ('Live Oak', 'Sutter'),
  ('Yuba City', 'Sutter'),
  ('Corning', 'Tehama'),
  ('Red Bluff', 'Tehama'),
  ('Tehama', 'Tehama'),
  ('Dinuba', 'Tulare'),
  ('Exeter', 'Tulare'),
  ('Farmersville', 'Tulare'),
  ('Lindsay', 'Tulare'),
  ('Porterville', 'Tulare'),
  ('Tulare', 'Tulare'),
  ('Visalia', 'Tulare'),
  ('Woodlake', 'Tulare'),
  ('Sonora', 'Tuolumne'),
  ('Camarillo', 'Ventura'),
  ('Fillmore', 'Ventura'),
  ('Moorpark', 'Ventura'),
  ('Ojai', 'Ventura'),
  ('Oxnard', 'Ventura'),
  ('Port Hueneme', 'Ventura'),
  ('Santa Paula', 'Ventura'),
  ('Simi Valley', 'Ventura'),
  ('Thousand Oaks', 'Ventura'),
  ('Ventura', 'Ventura'),
  ('Davis', 'Yolo'),
  ('West Sacramento', 'Yolo'),
  ('Winters', 'Yolo'),
  ('Woodland', 'Yolo'),
  ('Marysville', 'Yuba'),
  ('Wheatland', 'Yuba')
) AS c(city, county)
WHERE NOT EXISTS (
  SELECT 1
  FROM locations_reference l
  WHERE l.city = c.city
    AND l.state = 'CA'
);
